function [trialsMatrix,trialsNames, trialResNames]=Joystick2D_v3_Phase(PhaseName)

switch PhaseName
	case 'MotorOFF_Ll_FreeWater'
        trialsNames={'FreeWater','FreeWater_Fail',...
                     'L0 Force','L0 Force_Omission'};
        trialResNames={'FreeWater_Succ','FreeWater_Fail','FreeWater_Omission','FreeWater_Omission_Fail',...
                       'L0 Force_Succ','L0 Force_Fail','L0 Force_Omission','L0 Force_Omission_Fail'};                 
                 
        trialsMatrix=[...
        %  1.type, 2.proba,3.opto/not,  4.fail sound softcode  5.water deliver valve no,
        %  6.Marker 7.Y/N free water 8.Force on/off softcode  9.Go/Nogo cue
        %    10. NA
            1,     1,       0,       4,           1,                      double('o'), 1,0,1;...   
            2,     0,       0,       4,           1,                      double('s'), 0,0,0;...   
            3,     0,       0,       4,           1,                      double('d'), 0,0,0;...   
            4,     0,       0,       4,           1,                      double('s'), 0,0,0];    
 
 	case 'MotorOFF_L2_FixPosition' 
        trialsNames={'Pull','NoPull',...
                     'L0 Force','L0 Force_Omission'};
        trialResNames={'Pull_Succ','Pull_Fail','NoPull_Succ','NoPull_Fail',...
                        'L0 Force_Succ','L0 Force_Fail','L0 Force_Omission','L0 Force_Omission_Fail'};  
        trialsMatrix=[...
        %  1.type, 2.proba,3.opto/not,  4.fail sound softcode  5.water deliver valve no,
        %  6.Marker 7.Y/N free water 8.Force on/off softcode  9.Go/Nogo cue
        %    10. NA
            1,     1,       0,       2,           1,                      double('o'), 4,1,1;...   
            2,     0,       0,       2,           1,                      double('s'), 0,0,1;...   
            3,     0,       0,       2,           1,                      double('d'), 0,0,1;...   
            4,     0,       0,       2,           1,                      double('s'), 0,0,1];          
 
            
 case 'MotorON_L3_unexpectedF' 
        trialsNames={'CueF0','CueF1','UnCueF1'};
        trialResNames={'CueF0_Succ','CueF0_Fail',...
                       'CueF1_Succ','CueF1_Fail',...
                       'UnCueF1_Succ','UnCueF1_Fail'};  
        trialsMatrix=[...
        %  1.type, 2.proba,3.opto/not,  4.fail sound softcode  5.water deliver valve no,
        %  6.Marker 7.Y/N free water 8.Force on/off softcode  9.Go/Nogo cue
        %    10. NA
        
            1,     0.4,       0,       2,         1,                      double('o'), 4,1,2;...   
            2,     0.5,       0,       2,         1,                      double('o'), 4,1,1;...   %cued reward
            3,     0.1,       0,       2,         1,                      double('o'), 4,1,2];
  
  case 'MotorON_L4_unexpectedF0' 
        trialsNames={'CueF0','CueF1','UnCueF0'};
        trialResNames={'CueF0_Succ','CueF0_Fail',...
                       'CueF1_Succ','CueF1_Fail',...
                       'UnCueF0_Succ','UnCueF0_Fail'};  
        trialsMatrix=[...
        %  1.type, 2.proba,3.opto/not,  4.fail sound softcode  5.water deliver valve no,
        %  6.Marker 7.Y/N free water 8.Force on/off softcode  9.Go/Nogo cue
        %    10. NA
        
            1,     0.5,       0,       2,         1,                      double('o'), 4,1,2;...   
            2,     0.4,       0,       2,         1,                      double('o'), 4,1,1;...   %cued reward
            3,     0.1,       0,       2,         1,                      double('o'), 4,1,1];

    
     case 'MotorOn_L5_3Force'
        trialsNames={'L0 Force','L1 Force',...
                     'L2 Force','L3 Force'};
        trialResNames={'L0 Force_Succ','L0 Force_Fail','L1 Force_Succ','L1 Force_Fail',...
                       'L2 Force_Succ','L2 Force_Fail','L3 Force_Succ','L3 Force_Fail'};  
        trialsMatrix=[...
        %  1.type, 2.proba,3.opto/not,  4.fail sound softcode  5.water deliver valve no,
        %  6.Marker 7.Y/N free water 8.Force on/off softcode  9.Go/Nogo cue
        %    10. NA
            1,     0.1,           0,       2,         1,                      double('o'),   4,1,1;...   
            2,     0.1,           0,       2,         1,                      double('s'),   4,1,1;...   
            3,     0.8,           0,       2,         1,                      double('s'),   4,1,1;... 
            4,     0,             0,       2,         1,                      double('d'),   4,1,1];          
        

    case 'MotorOn_L6_Opto'
        trialsNames={'L0 Force','L1 Force',...
                     'L2 Force','Opto'};
        trialResNames={'L0 Force_Succ','L0 Force_Fail','L1 Force_Succ','L1 Force_Fail',...
                       'L2 Force_Succ','L2 Force_Fail','Opto_Succ','Opto_Fail'};  
        trialsMatrix=[...
        %  1.type, 2.proba,3.opto/not,  4.fail sound softcode  5.water deliver valve no,
        %  6.Marker 7.Y/N free water 8.Force on/off softcode  9.Go/Nogo cue
        %    10. NA
            1,     0,              0,       2,         1,                      double('o'),   4,1,1;...   
            2,     0,              0,       2,         1,                      double('s'),   4,1,1;...   
            3,     0,              0,       2,         1,                      double('s'),   4,1,2;... 
            4,     1,              1,       2,         1,                      double('d'),   4,1,2];          

    case 'MotorOn_RwdOmission'
        trialsNames={'RwdOmission','ForceOmi',...
                     'L2 Force','RwdHigher'};
        trialResNames={'RwdOmi_Succ','RwdOmi_Fail','ForceOmi_Succ','ForceOmi_Fail',...
                       'L2 Force_Succ','L2 Force_Fail','RwdHigher_Succ','RwdHigher_Fail'};  
        trialsMatrix=[...
        %  1.type, 2.proba,3.opto/not,  4.fail sound softcode  5.water deliver valve no,
        %  6.Marker 7.Y/N free water 8.Force on/off softcode  9.Go/Nogo cue
        %    10. NA
            1,     0.1,       0,      2,         1,                           double('o'),   4,1,1;...   
            2,     0,         0,      2,         1,                           double('s'),   4,1,1;...   
            3,     0.8,       0,      2,         1,                           double('s'),   4,1,1;... 
            4,     0.1,       0,      2,         1,                           double('s'),   4,1,1];    
    
      case 'MotorOn_RLForce'
        trialsNames={'L0 Force','L Force',...
                     'R Force'};
        trialResNames={'L0 Force_Succ','L0 Force_Fail','L Force_Succ','L Force_Fail',...
                        'R Force_Succ','R Force_Fail'};  
        trialsMatrix=[...
        %  1.type, 2.proba,3.opto/not,  4.fail sound softcode  5.water deliver valve no,
        %  6.Marker 7.Y/N free water 8.Force on/off softcode  9.Go/Nogo cue
        %    10. NA
            1,     0.8,           0,       2,         1,                      double('o'),   4,1,1;...   
            2,     0.1,           0,       2,         1,                      double('s'),   4,1,1;...   
            3,     0.1,           0,       2,         1,                      double('s'),   4,1,1];            
end     
end