function figData=Online_LickinJoystick(action,TrialSequence,trialMatrix,Phase,trialsNames,trialsResNames,figData,currentTrial,outcome,trialType,newxdata)
%figData=OnlinePlot(action,TrialSequence,trialMatrix,subPlotTitles,figData,currentTrial,outcome,trialType,newxdata)
%This function initializes ("ini") or updates ("update") a figure to monitor online the trial sequence and the lick events. 
%Initialization requiers the "TrialSequence" and the parameters of the trials contained in the "trialMatrix". 
%Subplots are named according to "subPlotTitles". "Phase" is used for the figure legend
%"currenTrial" and "outcome" arguments are used to update the subplot for trials
%"trialType" and "newxdata" arguments are used to update the subplot for licks
%
%"outcome" and "newxdata" arguments are generated by "Online_LickEvents" function.
%
%The output structure is used to update the plot and contains :
%figData.figPlot        :handles the figure properties
%       .trialusbplot   :handles the subplot for trial (axes)
%       .curTrialplot   :handles the current trial plot (a line)
%       .trialsplot     :handles the plots for eachtrials (data)
%       .licksubplot    :handles the subplot for lick (axes)
%       .lickplot       :handles the plot for lick (data)
%
%function written by Quentin for CuedReinforcers bpod protocol

global BpodSystem S

plotSpan=10;  %plotting window
MS_trial=5;     %marker size for trial
MS_licks=1;     %marker size for lick
maxy=200;       %y axe for licks
ystep=25;       %y axe for licks

minx=S.GUI.TimeMin_lick;
maxx=S.GUI.TimeMax_lick;
xstep=1;    
xtickvalues=minx:xstep:maxx;

switch action
    case 'ini'
%%Close pre-existing plot and test parameters
if size(TrialSequence,1)==1
    TrialSequence=TrialSequence';
end


%% Close pre-existing plot and test parameters
try
    close 'Online LickinMotor Plot';
end


%% Create Figure
figPlot=figure('Name','Online LickinMotor Plot','Position', [1100 50 500 700], 'numbertitle','off');
hold on
ProtoSummary=sprintf('%s : %s -- %s - %s',...
    date, BpodSystem.GUIData.SubjectName, ...
    BpodSystem.GUIData.ProtocolName, Phase);
MyBox = uicontrol('style','text');
set(MyBox,'String',ProtoSummary, 'Position',[10,1,400,20]);

%% Trial plot
trialsubplot=subplot(5,2,[1 2]);
hold on
%Specify legend and axes
plot(-20,-20,'ko','MarkerSize',MS_trial); %circle legend, ie reward
plot(-20,-20,'ks','MarkerSize',MS_trial); %square legend, ie omission
plot(-20,-20,'kd','MarkerSize',MS_trial); %diamond legend, ie Large
plot(-20,-20,'ko','MarkerFaceColor','g','MarkerSize',MS_trial); %green legend, ie hit
plot(-20,-20,'ko','MarkerFaceColor','r','MarkerSize',MS_trial); %red legend, ie missed
% legend(S.Names.Symbols{S.GUI.Circle},S.Names.Symbols{S.GUI.Square},S.Names.Symbols{S.GUI.Diamond},'Hit','Missed','Location','east');
legend('boxoff');
title('Trials outcome');
xlabel('Trial Number');
set(trialsubplot,'XLim',[3-plotSpan 3+plotSpan],'YLim',[0 5],'YTick',[1 2 3 4],...
                        'YTickLabel',trialsNames, 'YTickLabelRotation', 45 );              
%Generates and handles plots for each trials and a current trial plot
curTrialplot=plot([1 1],[0 4],'-b');
for i=1:size(TrialSequence)
    for TrialSeq=1:size(TrialSequence,1)
        if TrialSequence(i)==TrialSeq
            trialsPlot(i)=plot(i,trialMatrix(TrialSeq,1),'LineStyle','none','marker',char(trialMatrix(TrialSeq,6)),'MarkerFaceColor','b', 'MarkerEdgeColor','k','MarkerSize',MS_trial);
        end
    end
end
hold off

%% Lick plot
%PlotParameters
labely='Trial number';
miny=0;                          
ytickvalues=miny:ystep:maxy;
labelx='Time from reward / cue (sec)';
%Subplot

trialsNames_8class=trialsResNames;


for i=1:size(trialsNames_8class,2)
    licksubplot(i)=subplot(5,2,i+2);
    hold on
    rewplot(i)=plot([0 0],[-5,500],'-r');
    lickplot(i)=plot([0 0],[1,500],'sk','MarkerSize',MS_licks,'MarkerFaceColor','k');
    set(lickplot, 'XData',[],'YData',[]);
    xlabel(labelx); 
    ylabel(labely);
    set(licksubplot,'XLim',[minx maxx],'XTick',xtickvalues,'YLim',[miny maxy],'YTick',ytickvalues,'YDir', 'reverse');
    title(trialsNames_8class{1,i});


set(licksubplot(i),'XLabel',[],'YLabel',[]);

end
%Save the figure properties
figData.fig=figPlot;
figData.trialsubplot=trialsubplot;
figData.trialsplot=trialsPlot;
figData.curTrialplot=curTrialplot;
figData.licksubplot=licksubplot;
figData.lickplot=lickplot;

    case 'update'
%% Trial Plot
%Change color of the last trial marker according to the oucome
set(figData.trialsplot(currentTrial),'MarkerFaceColor',outcome);
%Move the current trial plot and the plotting winow
set(figData.trialsubplot, 'XLim',[currentTrial-plotSpan+2 currentTrial+plotSpan+2]);
set(figData.curTrialplot,'XData', [currentTrial+1 currentTrial+1]);
        if 0<trialType<=8
%% LickPlot
%Extract the previous data from the plot
previous_xdata=get(figData.lickplot(trialType),'XData'); %lick time
previous_ydata=get(figData.lickplot(trialType),'YData'); %trial number

%initialize the first raster
if isempty(previous_ydata)==1
    trialTypeCount=1; 
else
    trialTypeCount=max(previous_ydata)+1;
end 
% 
% %Update the figure with the new licking data
updated_xdata=[previous_xdata newxdata];
newydata=linspace(trialTypeCount,trialTypeCount,size(newxdata,2));
updated_ydata=[previous_ydata newydata];
set(figData.lickplot(trialType),'XData',updated_xdata,'YData',updated_ydata);
        end
% %% Update GUI plot parameters
for i=1:size(trialsResNames,2)       
        set(figData.licksubplot(i),'XLim',[minx maxx],'XTick',xtickvalues);
end
end
end